name: Video Processing Workflow

on: [push]

jobs:
  process-video:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m venv env
        source env/bin/activate
        pip install yt-dlp
        pip install mysql-connector-python  # Si necesitas MySQL
        pip install ffmpeg-python  # Si necesitas ffmpeg-python

    - name: Run video processing script
      run: |
        source env/bin/activate
        python tu_script.py
      env:
        URL: ${{ secrets.M3U8_URL }}
        FILENAME: ${{ secrets.OUTPUT_FILENAME }}
